server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

scrape_configs:
- job_name: openethereum
  static_configs:
  - targets:
      - localhost
    labels:
      job: openethereum
      __path__: /log/oe/*log



